INSERT INTO developer(name,age,gender) VALUES ('Alexander',29,'male');
INSERT INTO developer(name,age,gender) VALUES ('Anna',23,'female');
INSERT INTO developer(name,age,gender) VALUES ('Alex',30,'male');
INSERT INTO skill (language,level_skill) VALUES('java','Senior');
INSERT INTO skill (language,level_skill) VALUES('js','Middle');
INSERT INTO skill (language,level_skill) VALUES ('C#','Middle');
INSERT INTO skill (language,level_skill) VALUES ('C++','Junior');
INSERT INTO skill (language,level_skill) VALUES ('java','Middle');
INSERT INTO projects (name_projects,language_projects) VALUES ('progect_1','java');
INSERT INTO projects (name_projects,language_projects) VALUES ('progect_2','js');
INSERT INTO projects (name_projects,language_projects) VALUES ('progect_3','C#');
INSERT INTO projects (name_projects,language_projects) VALUES ('progect_4','C++');
INSERT INTO companies (name_companies,country_companies) VALUES ('Dell Technologies','USA');
INSERT INTO companies (name_companies,country_companies) VALUES ('EPAM','Ukraine');
INSERT INTO companies (name_companies,country_companies) VALUES ('Samsung','Korea');
INSERT INTO customers (name_customers,country_customers) VALUES ('customer_1','Ukraine');
INSERT INTO customers (name_customers,country_customers) VALUES ('customer_2','USA');
INSERT INTO customers (name_customers,country_customers) VALUES ('customer_3','Korea');
INSERT INTO customers (name_customers,country_customers) VALUES ('customer_4','Japan');
INSERT INTO developers_skill (developer_id,skill_id) VALUES (1,1);
INSERT INTO developers_skill (developer_id,skill_id) VALUES (1,3);
INSERT INTO developers_skill (developer_id,skill_id) VALUES (2,2);
INSERT INTO developers_skill (developer_id,skill_id) VALUES (2,5);
INSERT INTO developers_skill (developer_id,skill_id) VALUES (3,4);
INSERT INTO developers_skill (developer_id,skill_id) VALUES (3,2);
INSERT INTO developers_skill (developer_id,skill_id) VALUES (3,1);
INSERT INTO developers_projects (developer_id,projects_id) VALUES (1,1);
INSERT INTO developers_projects (developer_id,projects_id) VALUES (2,1);
INSERT INTO developers_projects (developer_id,projects_id) VALUES (3,1);
INSERT INTO developers_projects (developer_id,projects_id) VALUES (2,2);
INSERT INTO developers_projects (developer_id,projects_id) VALUES (3,2);
INSERT INTO developers_projects (developer_id,projects_id) VALUES (1,3);
INSERT INTO developers_projects (developer_id,projects_id) VALUES (3,4);
INSERT INTO companies_projects (companies_id,projects_id) VALUES (1,1);
INSERT INTO companies_projects (companies_id,projects_id) VALUES (1,2);
INSERT INTO companies_projects (companies_id,projects_id) VALUES (2,2);
INSERT INTO companies_projects (companies_id,projects_id) VALUES (2,4);
INSERT INTO companies_projects (companies_id,projects_id) VALUES (3,3);
INSERT INTO companies_projects (companies_id,projects_id) VALUES (3,1);
INSERT INTO customers_projects (customers_id,projects_id) VALUES (1,1);
INSERT INTO customers_projects (customers_id,projects_id) VALUES (1,3);
INSERT INTO customers_projects (customers_id,projects_id) VALUES (2,4);
INSERT INTO customers_projects (customers_id,projects_id) VALUES (2,2);
INSERT INTO customers_projects (customers_id,projects_id) VALUES (3,1);
INSERT INTO customers_projects (customers_id,projects_id) VALUES (3,4);
INSERT INTO customers_projects (customers_id,projects_id) VALUES (4,2);
INSERT INTO customers_projects (customers_id,projects_id) VALUES (4,3);
